english_exercises_app/exercises/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.ExerciseShowView.as_view(), name="exercise_show"),
    path("upload/", views.ExerciseUploadView.as_view(), name="exercise_upload"),
    path("create/", views.ExerciseCreateView.as_view(), name="exercise_create"),
    path("stats/", views.ExerciseStatsView.as_view(), name="exercise_stats"),
    path(
        "stats/delete/",
        views.ExerciseStatsDeleteView.as_view(),
        name="exercise_stats_delete",
    ),
]

english_exercises_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('users/', include('english_exercises_app.users.urls')),
    path('exercises/', include('english_exercises_app.exercises.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

english_exercises_app/users/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("create/", views.UserCreateView.as_view(), name="user_create"),
    path("update/", views.UserPasswordUpdateView.as_view(), name="user_update"),
    path("delete/<int:pk>/", views.UserDeleteView.as_view(), name="user_delete"),
    path("settings/", views.UserSettingsView.as_view(), name="user_settings"),
    path("login/", views.UserLoginView.as_view(), name="user_login"),
    path("logout/", views.UserLogoutView.as_view(), name="user_logout"),
]

english_exercises_app/exercises/models.py
from django.conf import settings
from django.contrib.postgres.fields import ArrayField
from django.db import models
from django.utils.translation import gettext_lazy as _


class BaseFileModel(models.Model):
    """
    Base model for user files.
    Restricts user to have only one file uploaded.
    """

    file = models.FileField(upload_to="")
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    class Meta:
        abstract = True


class File(BaseFileModel):
    """
    Stores information about the current text file.
    """

    class Meta:
        verbose_name = _("File")
        verbose_name_plural = _("Files")


class AudioFile(BaseFileModel):
    """
    A class to store audio files.
    """

    class Meta:
        verbose_name = _("Audio file")
        verbose_name_plural = _("Audio files")


class Exercise(models.Model):
    """
    Stores information about user answers.
    """

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE
    )
    exercise_type = models.CharField(max_length=255)
    user_answer = models.CharField(max_length=255)
    correct_answer = models.CharField(max_length=255)
    flag = models.BooleanField()

    def save(self, *args, **kwargs):
        if self.user_answer == self.correct_answer:
            self.flag = True
        else:
            self.flag = False
        super().save(*args, **kwargs)

    def __str__(self):
        return (
            f'{self.exercise_type = }\n'
            f'{self.user_answer = }\n'
            f'{self.correct_answer = }\n'
            f'{self.flag = }'
        )

    class Meta:
        verbose_name = _("Exercise")
        verbose_name_plural = _("Exercises")


class Memory(models.Model):
    """
    Stores current parameters for exercises.
    Has method to increment number of current exercise.
    """

    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE
    )
    current_count = models.IntegerField(default=1)
    count = models.IntegerField()

    # this limits possible db options to postgres
    pos = ArrayField(base_field=models.CharField(max_length=63))

    exercise_type = models.CharField(max_length=255)
    length = models.IntegerField()
    skip_length = models.IntegerField()
    add_audio = models.BooleanField(blank=True, null=True)

    @classmethod
    def get_current_count(cls):
        counter, created = cls.objects.get_or_create(pk=1)
        return counter.current_count

    @classmethod
    def increment_count(cls):
        counter, created = cls.objects.get_or_create(pk=1)
        counter.current_count += 1

        if counter.current_count == counter.count:
            counter.delete()
        else:
            counter.count += 1
            counter.save()

english_exercises_app/users/models.py
# from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    pass

    class Meta:
        verbose_name = _("User")
        verbose_name_plural = _("Users")

english_exercises_app/exercises/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from text_processing.prepare_data import remove_data

from .models import Exercise, File, Memory


class FileForm(forms.ModelForm):
    """
    Form for file upload. Has file format check.
    1 entry per user.
    """

    file = forms.FileField(
        label=_("File"),
        widget=forms.FileInput(
            attrs={
                "class": "form-control",
                "type": "file",
            }
        )
    )

    class Meta:
        model = File
        fields = ["file"]

    def clean(self):
        """
        Checks file format.
        """

        cleaned_data = super().clean()

        file = cleaned_data.get("file")
        if file and not file._name.endswith(".txt"):
            raise forms.ValidationError(_("Incorrect file format"))

        return cleaned_data

    def save(self, user, commit=True):
        # delete previous files and db entry, if exist
        file = File.objects.filter(user=user).first()
        if file is not None:
            remove_data(file.file.path, str(user))  # rm associated json
            file.file.delete()
            file.delete()

        instance = super().save(commit=False)
        instance.user = user
        if commit:
            instance.save()
        return instance


class MemoryForm(forms.ModelForm):
    """
    Sets current parameters for exercise generation and stores them in
    Memory model. 1 entry per user.
    """

    count = forms.IntegerField(
        label=_("Count"),
        initial=50,
        widget=forms.NumberInput(
            attrs={
                "class": "form-range",
                "type": "range",
                "min": 1,
                "max": 99,
                "step": 1,
                "id": "rangeInput",
            }
        ),
    )
    pos = forms.MultipleChoiceField(
        label=_("Parts of speech"),
        choices=(
            ("ALL", _("All")),
            ("VERB", _("Verbs")),
            ("NOUN", _("Nouns")),
            ("ADJ", _("Adjectives")),
            ("DET", _("Articles")),
        ),
        initial="ALL",
        widget=forms.CheckboxSelectMultiple(
            attrs={
                "multiple": True,
            }
        ),
    )
    exercise_type = forms.ChoiceField(
        label=_("Exercise type"),
        choices=(
            ("all_choices", _("All")),
            ("type_in", _("Type in")),
            ("multiple_choice", _("Multiple choice")),
            ("word_order", _("Complete sentence")),
            ("blanks", _("Drag blanks")),
        ),
        widget=forms.Select(
            attrs={
                "class": "form-select",
            }
        ),
    )
    length = forms.IntegerField(
        max_value=10,
        min_value=1,
        initial=1,
        label=_("Context length"),
        widget=forms.NumberInput(attrs={"class": "form-control"}),
    )
    skip_length = forms.IntegerField(
        max_value=5,
        min_value=3,
        initial=3,
        label=_("Skipped words (complete sentence exercises only)"),
        widget=forms.NumberInput(attrs={"class": "form-control"}),
    )
    add_audio = forms.BooleanField(
        required=False,
        initial=False,
        label=_("Enable audio (slows down generation)"),
        widget=forms.CheckboxInput(attrs={"class": "form-check-input"}),
    )

    class Meta:
        model = Memory
        fields = ["count", "pos", "exercise_type", "length", "skip_length", "add_audio"]

    def save(self, user, commit=True):
        # delete previous entry, if exists
        memory = Memory.objects.filter(user=user).first()
        if memory is not None:
            memory.delete()

        instance = super().save(commit=False)
        instance.user = user
        if commit:
            instance.save()
        return instance


class TypeInExercise(forms.ModelForm):
    """
    Base form for all types of exercises.
    """

    begin = forms.CharField(
        max_length=4095,
        widget=forms.HiddenInput(),
    )
    end = forms.CharField(
        max_length=2047,
        widget=forms.HiddenInput(),
        required=False
    )
    hint = forms.CharField(
        max_length=255,
        widget=forms.HiddenInput(),
    )
    count = forms.IntegerField(widget=forms.HiddenInput())
    current_count = forms.IntegerField(widget=forms.HiddenInput())

    class Meta:
        model = Exercise
        fields = ["user_answer", "exercise_type", "correct_answer"]
        widgets = {
            "user_answer": forms.TextInput(attrs={"class": "form-control"}),
            "exercise_type": forms.HiddenInput(),
            "correct_answer": forms.HiddenInput(),
        }

    def save(self, user, commit=True):
        instance = super().save(commit=False)
        instance.user = user
        if commit:
            instance.save()
        return instance


class MultipleChoiceExercise(TypeInExercise):
    """
    Used for both multiple choice and word order exercises.
    """

    user_answer = forms.ChoiceField(
        widget=forms.Select(
            attrs={
                "class": "form-select",
            }
        ),
    )


class BlanksExercise(TypeInExercise):
    user_answer = forms.CharField(
        widget=forms.HiddenInput(),
        # widget=forms.RadioSelect(
        #     attrs={
        #         "class": "form-check-label",
        #         "type": "radio",
        #     }
        # ),
    )
    answers = forms.CharField(
        widget=forms.HiddenInput(),
    )

english_exercises_app/users/forms.py
from django.contrib.auth.forms import (
    AuthenticationForm,
    PasswordChangeForm,
    UserCreationForm,
)
from django.utils.translation import gettext_lazy as _

from .models import User


class RegistrationForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].widget.attrs.update(
            {
                "maxlength": "50",
                "class": "form-control",
                "placeholder": _("Username"),
            }
        )
        self.fields["username"].help_text = _(
            "Required. 50 characters or fewer. Letters, digits and @/./+/-/_ only."  # noqa: E501
        )
        self.fields["password1"].widget.attrs.update(
            {"class": "form-control", "placeholder": _("Password")}
        )
        self.fields["password2"].widget.attrs.update(
            {"class": "form-control", "placeholder": _("Repeat password")}
        )

    class Meta(UserCreationForm.Meta):
        model = User
        fields = [
            "username",
            "password1",
            "password2",
        ]


class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].widget.attrs.update({"class": "form-control"})
        self.fields["password"].widget.attrs.update({"class": "form-control"})


class PasswordUpdateForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["old_password"].widget.attrs.update({"class": "form-control mt-1"})
        self.fields["new_password1"].widget.attrs.update({"class": "form-control mt-1"})
        self.fields["new_password2"].widget.attrs.update({"class": "form-control mt-1"})

english_exercises_app/users/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import CreateView, DeleteView, TemplateView

from english_exercises_app.mixins import MessagesMixin

from .forms import LoginForm, PasswordUpdateForm, RegistrationForm
from .models import User


class UserCreateView(MessagesMixin, CreateView):
    form_class = RegistrationForm
    template_name = "users/create.html"
    success_message = _("User created successfully!")
    success_url = reverse_lazy("user_login")


class UserPasswordUpdateView(MessagesMixin, LoginRequiredMixin, PasswordChangeView):
    form_class = PasswordUpdateForm
    model = User
    template_name = "users/update.html"
    success_message = _("Password updated successfully!")
    permission_denied_message = _("Please log in.")
    success_url = reverse_lazy("home")
    login_url = reverse_lazy("user_login")


class UserDeleteView(MessagesMixin, LoginRequiredMixin, DeleteView):
    template_name = "users/delete.html"
    model = User
    success_message = _("User deleted successfully!")
    permission_denied_message = _("Please log in.")
    success_url = reverse_lazy("home")
    login_url = reverse_lazy("user_login")

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.User == request.user:
            success_url = self.get_success_url()
            self.object.delete()
            return redirect(success_url)
        else:
            messages.error(self.request, _("You may only delete your own profile."))
            return redirect("home")


class UserSettingsView(LoginRequiredMixin, TemplateView):
    template_name = "users/settings.html"
    login_url = reverse_lazy("user_login")
    permission_denied_message = _("Please log in.")


class UserLoginView(MessagesMixin, LoginView):
    template_name = "users/login.html"
    authentication_form = LoginForm
    success_message = _("Logged in successfully!")


class UserLogoutView(LogoutView):
    def dispatch(self, request, *args, **kwargs):
        messages.success(request, _("You are logged out"))
        return super().dispatch(request, *args, **kwargs)

english_exercises_app/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView


class HomePageView(TemplateView):
    def get(self, request, *args, **kwargs):
        return render(request, "base.html")

english_exercises_app/templates/exercises/create.html
{% extends "base.html" %}
{% load i18n %}

{% block main %}

  <style>
    .wrapped-word {
      word-wrap: break-word;
      min-width: 100px;
      max-width: 130px;
    }
  </style>

  <div class="ms-1">
    <h1 class="text-left mb-4">{% translate 'Exercises' %}</h1>

    <div class="row justify-content-left col-auto col-lg-6">
      <form action="{% url 'exercise_create' %}" method="post" class="needs-validation" novalidate>
        <div class="form-group">
          {% csrf_token %}
          <table class="table table-hover table-borderless" required>
              {% for field in form %}
                <tr>
                  <th class="align-middle">{{ field.label_tag|slice:":-9" }}</th>
                  <td>
                    {{ field }}
                    {% if field.name == "count" %}
                      <label for="rangeInput" id="rangeValue" class="col-12 d-flex flex-row-reverse">{{ form.count.value }}</label>
                    {% endif %}
                  </td>
                </tr>
              {% endfor %}
          </table>
          <div class="col-12 d-flex flex-row-reverse">
            <input class="btn btn-outline-success btn-md col-lg-3 col-md-3 col-sm-4 text-uppercase" type="submit" value="{% translate 'Generate' %}">
          </div>
        </div>
      </form>
    </div>

    <!-- Adds value to slider. -->
    <script>
      const rangeInput = document.getElementById('rangeInput');
      const rangeValue = document.getElementById('rangeValue');

      rangeInput.addEventListener('input', updateValue);

      function updateValue() {
        rangeValue.textContent = rangeInput.value;
      }
    </script>
  </div>

{% endblock %}


english_exercises_app/templates/exercises/show.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}

{% block main %}

  <div class="container wrapper flex-grow-1">

    <div class="card" >

      <div class="card-header bg-secondary text-white">
        <h2>{% translate 'Exercise' %} # {{ form.current_count.value }} / {{ form.count.value }}</h2>
      </div>


      <div class="card-body bg-light">
        <form action="{% url 'exercise_show' %}" method="post" class="needs-validation" novalidate>
          <div class="form-group">
            {% csrf_token %}

            <h4 class="text-muted font-weight-light my-3 ms-1">{{ form.hint.value }}</h4>
            <hr>

            {% if form.exercise_type.value != "blanks" %}
              <table class="table table-hover table-borderless" required>
                <tr>
                  <td class="row">
                    <div class="align-items-center">
                        {{ form.begin.value }}
                        <span class="p-2 col-auto d-inline-flex">
                          {{ form.user_answer }}
                        </span>
                        {% if correct_answer %}
                          <span class="text-secondary fw-lighter me-2">(<span class="text-success fw-bold">{{ correct_answer }}</span>)</span>
                        {% endif %}
                        {{ form.end.value }}
                    </div>
                  </td>
                </tr>
              </table>
            {% endif %}

	    {% if form.exercise_type.value == "blanks" %}
              <input type="hidden" id="id_user_answer" name="user_answer" value=""></input>
              <input type="hidden" id="id_answers" name="answers" value="{{ form.answers.value }}"></input>

              <!-- render text -->
              <div class="row">
                <div class="align-items-center mb-2 mt-3">
                {% for item in form.begin.value|split:".#.#." %}
                  {{ item }}
                  {% if not forloop.last %}
                  <div class="content-task d-inline-flex col-auto justify-content-center">
                    <ul class="questions text-justify">
                      <li class="dropzone custom-number-{{ forloop.counter0 }}"><span class="word-empty">{{ forloop.counter }}</span></li>
                    </ul>
                  </div>
                  {% endif %}
                {% endfor %}
                </div>
              </div>

            <!-- show draggable answers -->
            {% if form.answers.value %}
              <div class="content-task my-3">
                <ul class="answers">
                  {% for option in form.answers.value|split:", " %}
                  <li class="dropzone"><span class="btn btn-outline-dark word-fill" data="{{ forloop.counter0 }}" draggable="true">{{ option}}</span></li>
                  {% endfor %}
                </ul>
              </div>
              {% endif %}

            <!-- show correct answers after post request -->
              {% if form.user_answer.value %}
                <div class="p-2 col-auto mt-3">
                  {% translate "Your answers:" %} {{ form.user_answer.value }}
                </div>
                <div class="text-secondary fw-lighter p-2 col-auto">{% translate "Correct answers:" %} <span class="text-success fw-bold">{{ correct_answer }}</span></div>
              {% endif %}

            {% endif %}

            {% for field in form %}
              {% if field.name != "user_answer" and field.name != "answers" %}
                <input type="hidden">{{ field }}</input>
              {% endif %}
            {% endfor %}

            <div class="col-12 d-flex flex-row-reverse">
              {% if button_status %}
                <a href="{% url 'exercise_show' %}?next=true" class="btn btn-outline-primary btn-md col-auto text-uppercase ms-3">{% translate 'Next' %}</a>
              {% else %}
                <a href="{% url 'exercise_show' %}" class="btn btn-outline-secondary btn-md col-auto text-uppercase ms-3">{% translate 'Skip' %}</a>
              {% endif %}
              <input {{ button_status }} class="btn btn-outline-success btn-md col-lg-3 col-md-3 col-sm-4 text-uppercase" type="submit" value="{% translate 'Check' %}">
            </div>

          </div>
        </form>

      {% if audio %}
        <p>Listen to audio:</p>
        <audio controls>
          <source src="{{ audio.file.url }}" type="audio/wav">
            Your browser does not support the audio element.
        </audio>
      {% endif %}

      </div>
    </div>

  </div>


<style>
  .content-task ul {
    height: 1.5em;
    padding-left: 0em;
  }
  .content-task ul li {
    list-style-type: none;
    display: inline-block;
    min-height: 2.3em;
    min-width: 5em;
    text-align: center;
  }
  .content-task ul li span {
    display: inline-block;
    cursor: pointer !important;
  }
  .content-task ul li span[draggable=true] {
    cursor: grab !important;
  }
  .content-task ul li span[draggable=true]:active {
    cursor: grabbing !important;
  }
  .content-task ul li span.word-empty {
    border-bottom: 1px solid #000;
    min-width: 0.5em;
  }
</style>


<script>
  // drag and drop

  var listOfStrings = [];
  const classToIndexMap = {
      "custom-number-0": 0,
      "custom-number-1": 1,
      "custom-number-2": 2,
      "custom-number-3": 3,
      "custom-number-4": 4
  };

  let dragged;
  document.addEventListener(
    "dragstart",
    function (e) {
      dragged = e.target;
      e.dataTransfer.setData("text", null);
    },
    false
  );
  document.querySelectorAll(".dropzone").forEach((el) =>
    el.addEventListener(
      "dragover",
      function (e) {
        e.preventDefault();
      },
      false
    )
  );
  document.addEventListener(
    "dragenter",
    function (e) {
      if (e.target.classList.contains("dropzone")) {
        e.target.style.border = "2px dashed #ccc";
      }
    },
    false
  );
  document.addEventListener(
    "dragleave",
    function (e) {
      if (e.target.classList.contains("dropzone")) {
        e.target.style.border = "";
      }
    },
    false
  );
  document.addEventListener(
    "drop",
    function (e) {
      e.preventDefault();
      if (e.target.classList.contains("dropzone")) {
        dragged.parentElement.removeChild(dragged);
        e.target.firstChild && e.target.removeChild(e.target.firstChild);
        e.target.appendChild(dragged);
        e.target.style.border = "";

        // remembering user input
        var draggedText = dragged.textContent;
        var userAnswerField = document.getElementById("id_user_answer");
        var dropTargetClass = e.target.classList;

        for (var i = 0; i < dropTargetClass.length; i++) {
          if (dropTargetClass[i].startsWith("custom-number-")) {
            dropBoxClass = dropTargetClass[i];
            dropBoxNumber = classToIndexMap[dropBoxClass]
            break;
          }
        }
        listOfStrings[dropBoxNumber] = draggedText;
        var concatenatedString = listOfStrings.join(", ");

        userAnswerField.value = concatenatedString;
      }
    },
    false
  );
</script>

{% endblock %}

english_exercises_app/templates/exercises/stats.html
{% extends "base.html" %}
{% load i18n %}

{% block main %}

  <div class="container wrapper d-flex justify-content-center">

    <div class="card col-md-12 col-sm-12 col-lg-6">

      <div class="card-header bg-secondary text-white">
        <h2>{% translate 'Stats' %}</h2>
      </div>

      <div class="card-body bg-light">

        <table class="table table-hover table-borderless" required>
          <tr>
            <th class="align-middle">{% translate "Total exercises completed:" %}</th>
            <td>{{ total_count }}</td>
          </tr>
          <tr>
            <th class="align-middle">{% translate "Correct answers:" %}</th>
            <td> {{ correct_answers }}</td>
          </tr>
          <tr>
            <th class="align-middle">{% translate "% of correct answers (last 100 exercises):" %}</th>
            <td>{{ percentage }}</td>
          </tr>
        </table>

      </div>
    </div>

  </div>

  <div class="container wrapper d-flex justify-content-end col-md-12 col-sm-12 col-lg-6">
    <a class="btn btn-secondary mt-3 text-uppercase" href="{% url 'exercise_stats_delete' %}">Reset stats</a>
  </div>
{% endblock %}

english_exercises_app/templates/exercises/stats_delete.html
{% extends "base.html" %}
{% load i18n %}

{% block main %}
  <div class="container wrapper flex-grow-1">
    <h1 class="my-4">
      {% translate 'Delete stats' %}
    </h1>
    <p>{% translate 'Are you sure you want to delete your stats, ' %}<span style="font-weight:bold"> {{ request.user.username }}</span>? {% translate 'This action cannot be undone.' %}</p>
    <form action="{% url 'exercise_stats_delete' %}" method="post" rel="nofollow">
      {% csrf_token %}
      <input class="btn btn-danger mt-2" type="submit" value="{% translate 'Yes, delete my stats' %}">
    </form>
  </div>
{% endblock %}


english_exercises_app/templates/exercises/upload.html
{% extends "base.html" %}
{% load i18n %}

{% block main %}
  {% url 'exercise_upload' as default_url %}
  <form action="{{ url_|default:default_url }}" method="post" novalidate enctype="multipart/form-data">
    <div class="form-group">
      <div class="row justify-content-center">
        <div class="{{ w1|default:'col-lg-6 col-md-12 col-sm-12' }}">
          {% csrf_token %}
          <p class="text-secondary">
            {% translate "Please upload a text file. Possible formats: .txt" %}
            <br>
            {% translate "Uploading a new file deletes your previous entry." %}
            <br>
              {% translate "If you don't know what to upload you may find some options" %} <a href=https://www.gutenberg.org/browse/scores/top#books-last7>{% translate "here." %}</a>
          </p>
          <table class="table table-hover table-borderless align-middle">
            {% for field in form %}
              <tr>
                <th>{{ field.label_tag|slice:":-9" }}</th>
                <td>
                  {{ field }}
                  {% if field.errors %}
                    <div class="text-secondary mt-3">{{ field.errors}}</div>
                  {% endif %}
                </td>
              </tr>
            {% endfor %}
          </table>
          <div class="col-12 d-flex flex-row-reverse">
            {% translate "Upload" as default_button %}
            <input class="btn btn-success btn-md col-lg-3 col-md-4 col-sm-6 text-uppercase" type="submit" value="{{ button|default:default_button }}">
          </div>
        </div>
      </div>
    </div>
  </form>
  {% endblock %}